{{- $username := required "Git username is required" .Values.git.username }}
{{- $personalAccessToken := required "Git personal access token is required" .Values.git.personalAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitops-cd-secret.name" . }}
  labels:
    app: gitops-cd
    app.kubernetes.io/instance: gitops-cd
    app.kubernetes.io/name: gitops-cd
    group: catalyst-tools
type: Opaque
stringData:
  GITOPS_CD_URL: {{ printf "https://%s:%s@%s/%s/%s.git" $username $personalAccessToken .Values.git.host .Values.git.org .Values.git.repo | quote }}
